### ISSUE TITLE
微服务（二） | a1ycesoft

### ISSUE THREAD

**Issue by a1ycesoft** [a1ycesoft/gittalk#1]
http://www.a1ycesoft.fun/posts/b7204284/? 

 day08Sentinel雪崩问题微服务调用链路中的某个服务故障，引起整个链路中所有微服务不可用，这就是雪崩。 雪崩问题解决方法：  超时处理：设定超时时间，不会无休止等待。 舱壁模式：限制某个业务能使用的线程数，避免耗尽整个tomcat资源，因此也叫线程隔离。 熔断降级：由断路器统计业务执行的异常比例，如果超出阈值会熔断该业务，拦截方法问到该业务的一切请求。 流量控制：限制业务访问的QPS，避免

**Comment by a1ycesoft** [comment]
测试。。。

**Comment by a1yce015** [comment]
test。。。
